### ISSUE TITLE
按文档部署服务不成功，是文档的问题还是其他问题？

### ISSUE THREAD

**Issue by charliexp** [phodal/lan#11]

**Comment by charliexp** [comment]
文档能不能写清楚一下呢？

**Comment by phodal** [comment]
@ charliexp 你不把问题写出来，怎么知道哪的问题?

**Comment by charliexp** [comment]
你是在windows下安装部署的还是Linux下，我在npm install 就有一些问题，好像版本依赖的问题，还有数据库的问题，我对nodejs不熟，在学习阶段，不好意思，还有npm 安装很慢，有什么解决办法？谢谢！

**Comment by phodal** [comment]
@charliexp 这些都是环境问题。。和文档本身没有多大问题。。

npm 可以淘宝的： http://npm.taobao.org/
其他的就没办法了。

**Comment by charliexp** [comment]
好的，可以用了，就是用你的测试程序有以下错误
![image](https://cloud.githubusercontent.com/assets/12693198/12028593/851f5a2a-ae14-11e5-80cc-98a97a5f64b8.png)

**Comment by phodal** [comment]
前端发的JSON有问题？

**Comment by charliexp** [comment]
curl --user root:root -X PUT -d '{ "dream": 1 }' -H "Content-Type: application/json" http://localhost:8899/topics/root

**Comment by charliexp** [comment]
就是这个

**Comment by phodal** [comment]
@charliexp 欢迎测试哈~~

**Comment by charliexp** [comment]
后续测试测试，这个项目很好！

**Comment by phodal** [comment]
求分享哈。。

**Comment by charliexp** [comment]
哈哈！以后要多请教你啊

**Comment by charliexp** [comment]
curl --user root:root -X PUT -d "{ \"dream\": 1 }" -H "Content-Type: application/json" http://localhost:8899/topics/root

这样提交才可以，不支持单引号的。
