### ISSUE TITLE
lan 崩溃

### ISSUE THREAD

**Issue by charliexp** [phodal/lan#12]
![image](https://cloud.githubusercontent.com/assets/12693198/12045226/5962f470-aeda-11e5-85b2-87e2e8998844.png)
这是什么原因？

**Comment by phodal** [comment]
node-coap挂了

**Comment by charliexp** [comment]
![image](https://cloud.githubusercontent.com/assets/12693198/12047510/c0e56c7c-af07-11e5-8668-073bbc1fd12f.png)
Mongodb不停连接是什么状况？

**Comment by phodal** [comment]
取数据就需要连接。。

**Comment by charliexp** [comment]
发送数据的客户端都关掉还会不停地连接，最后lan退出，稳定还是不行

**Comment by charliexp** [comment]
不知道是不是我的机器的问题

**Comment by phodal** [comment]
@charliexp OK，似乎是Node CoAP库的问题。

**Comment by charliexp** [comment]
不知道Linux下会不会好些

**Comment by phodal** [comment]
给下步骤

**Comment by charliexp** [comment]
我在家里的电脑没有发生着个问题，公司电脑是用ＭＱＴＴ推送１２万消息后发生coap get卡住，后lan崩溃。
