### ISSUE TITLE
npm jobs/cron.js 执行不了

### ISSUE THREAD

**Issue by xinshouke** [phodal/lan#13]
我去phodal-archive/lan-jobs-cron下载了cron.js 和sqlite2mongodb.js，执行npm jobs/cron.js 依然不成功，不知道为什么
[root@cent63 lan]# npm jobs/cron.js 

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, upgrade,
    v, verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.10.1 /root/node0124x64/lib/node_modules/npm

**Comment by phodal** [comment]
Hi @xinshouke 应该是 node  jobs/cron.js ， 打错了哈。我更新一下文档
