### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by yinwz** [phodal/lan#15]
Centos 7.2.1511_X64
安装到 sequelize db:migrate时出错，
Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /usr/lib/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
[Error: The dialect sqlite is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite. (Error: Please install sqlite3 package manually)]

很无语啊，sqlite3确实安装了

**Comment by phodal** [comment]
换个数据库试试？

**Comment by yinwz** [comment]
改为mysql，可以

**Comment by phodal** [comment]
@yinwz 会不会是没装sqlite的库？

**Comment by yinwz** [comment]
无论是yum install sqlite
还是npm install sqlite
都确实安装了
