### ISSUE TITLE
CentOS 6.5 32bit Installation Guide

### ISSUE THREAD

**Issue by crazydiamondzgy** [phodal/lan#2]
## Install CentOS 6.5 32bit

why CentOS 6.5, not 7.0. Because I hope I can build a Environment with the least cost. I choose the CentOS 6.5 which can work perfectly in a 512MB RAM computer.

## Install  MongoDB

1. Download mongodb-linux-i686-3.0.5.gz for the 32bit linux system
2. Shutdown SELINUX
vi /etc/selinux/config  
#SELINUX=enforcing  
#SELINUXTYPE=targeted  
SELINUX=disabled  
:wq!  
setenforce 0  
3. tar zxvf mongodb-linux-i686-3.0.5.gz
4. mv mongodb-linux-i686-3.0.5  /usr/local/mongodb
5. mkdir  -p  /data/mongodb/mongodb_data/
6. mkdir  -p  /data/mongodb/mongodb_log/ 
7. /usr/local/mongodb/bin/mongod --port 27017 --fork --dbpath=/data/mongodb/mongodb_data/ --logpath=/data/mongodb/mongodb_log/mongodb.log --logappend

## Install sqlite3

1. make sure your connected to the internet
2. yum install sqlite

## Install node.js

1. download node-v0.12.7-linux-x86.tar.gz for 32bit os
2. tar zxvf node-v0.12.7-linux-x86.tar.gz
3. mv node-v0.12.7-linux-x86.tar  /usr/local/nodejs
4. export PATH=$PATH:/usr/local/nodejs/bin/

## Install lan

1. download lan-master.zip via  https://codeload.github.com/phodal/lan/zip/master
2. yum install unzip 
3. unzip lan-master.zip
4. cd lan-master
5. npm install

**Comment by phodal** [comment]
move to wiki: https://github.com/phodal/lan/wiki/CentOS-6.5-32bit-Installation-Guide
