### ISSUE TITLE
我想问下，这个包中间有mqtt broker吗？

### ISSUE THREAD

**Issue by zengleyi** [phodal/lan#23]
对不起，我是level 0 程序员，我想问下，这个包中间有mqtt broker吗？我翻了下没有看到。如果没有，你当时这个项目用的是什么mqtt broker？我想找个好点的开源broker运行在自己的服务器上，但是mosca太过陈旧并且有很多问题。谢谢你！

**Comment by phodal** [comment]
最开始的 MQTT.js 提供了，我记得现在好像没有了

**Comment by zengleyi** [comment]
非常谢谢你的及时回复，我是在文件中看到有mqtt.MqttServer()的方法，我还以为是你自定义了一个broker呢。非常感谢你，大牛！

**Comment by phodal** [comment]
以前的 mqtt.js 里是有的，哈哈
