### ISSUE TITLE
建议你把 auth 信息放到  URI-QUERY

### ISSUE THREAD

**Issue by crazydiamondzgy** [phodal/lan#3]
理由是：
1） 目前常规方案
2） 使用 coap-client , copper 都可以简单通信
3） BLOCK2 不是RFC7252 核心部分， 有可能跟其它实现不兼容

**Comment by phodal** [comment]
coap://111.222.333.444/id/1?root:root

**Comment by crazydiamondzgy** [comment]
如果是加密模式，可以是coap://111.222.333.444/id/1?auth=BD3CA982379734EF 模式
具体步骤，先将用户名密码 root:root DES AES 加密成 binary，然后将 binary base64 转换成可见模式
