### ISSUE TITLE
2个疑问

### ISSUE THREAD

**Issue by crazydiamondzgy** [phodal/lan#6]
1）我发送一个 CON 包，服务器应答了3次，可用我的 ucoap 直接编译测试
2）post 上去的数据，并不是替换原来数据，而是无限附加到数据后面

**Comment by phodal** [comment]
1. 问题没说清楚?
2. 现在返回的是所有的结果? 要有这种需求?

**Comment by crazydiamondzgy** [comment]
问题1已经解决，原来 message_id 只能传非0的值

现在是问题2， 为什么 post 过去的数据不是覆盖原来的数据，而是不断叠加，设计的初衷是什么

**Comment by phodal** [comment]
@crazydiamondzgy 

问题2，那个数据是存在的，不会被替换掉。。会生成一个新的，最后返回这个用户的所有结果

**Comment by phodal** [comment]
see in https://github.com/phodal/lan/issues/7
